# Generated by Django 5.2.17 on 2026-08-19 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("openings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionMetric",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fields_emitted", models.IntegerField(default=0)),
                ("fields_accepted", models.IntegerField(default=0)),
                (
                    "fields_rejected_citation",
                    models.IntegerField(
                        default=0,
                        help_text="Cited an element_id not in the supplied set (§5.6 check 1).",
                    ),
                ),
                (
                    "fields_rejected_grounding",
                    models.IntegerField(
                        default=0,
                        help_text="Value not present in the text it cited (§5.6 check 2).",
                    ),
                ),
                ("fields_flagged_low_confidence", models.IntegerField(default=0)),
                ("fields_null_with_citation", models.IntegerField(default=0)),
                (
                    "schema_repair_retries",
                    models.IntegerField(
                        default=0,
                        help_text="At most one per call, and only for malformed JSON (§5.6).",
                    ),
                ),
                (
                    "extraction_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="openings.extractionrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "OPENING"),
                            ("FIELD_PROVENANCE", "FIELD_PROVENANCE"),
                            ("QUOTE_LINE", "QUOTE_LINE"),
                            ("MATCH", "MATCH"),
                            ("DOCUMENT_MANIFEST", "DOCUMENT_MANIFEST"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField(db_index=True)),
                ("field_name", models.CharField(max_length=100)),
                ("value_before", models.TextField(blank=True, null=True)),
                ("value_after", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "used_for_training",
                    models.BooleanField(
                        default=False, help_text="Promoted into the golden set (§5.10)."
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "extraction_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_records",
                        to="openings.extractionrun",
                    ),
                ),
                (
                    "field_provenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_records",
                        to="openings.fieldprovenance",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="feedback_fe_entity__e5c30c_idx",
                    ),
                    models.Index(
                        fields=["extraction_run", "field_name"],
                        name="feedback_fe_extract_0a3247_idx",
                    ),
                    models.Index(
                        fields=["field_name", "changed_at"],
                        name="feedback_fe_field_n_8e5053_idx",
                    ),
                ],
            },
        ),
    ]
