# Generated by Django 5.2.17 on 2026-08-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionmetric',
            name='hardware_callouts',
            field=models.IntegerField(default=0, help_text='Distinct hardware-group callouts found in the door schedule.'),
        ),
        migrations.AddField(
            model_name='extractionmetric',
            name='hardware_components_written',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extractionmetric',
            name='hardware_sets_resolved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extractionmetric',
            name='hardware_sets_unresolved',
            field=models.IntegerField(default=0, help_text='Callout present, definition not in the document. Never guessed.'),
        ),
    ]
