# Generated by Django 5.2.17 on 2026-08-19 12:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("openings", "0001_initial"),
        ("pricing", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("APPROVED", "APPROVED"),
                            ("EXPORTED", "EXPORTED"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "subtotal_sale",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "freight_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="NULL renders as 'TBD'. Freight is a line with a nullable amount, never a computed number (C11): FR-7 requires the line, and CBC confirmed freight is generally not quoted at estimate stage.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tax_jurisdiction",
                    models.CharField(
                        blank=True,
                        help_text="Two-letter state code. Only OH and KY are taxable (§1.1).",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "tax_rate_applied",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="The rate actually used, stored so the quote reproduces after a rate change.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "terms_version",
                    models.CharField(
                        blank=True,
                        help_text="Standard commercial terms applied at export (FR-10).",
                        max_length=50,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "export_key",
                    models.CharField(
                        blank=True,
                        help_text="Rendered PDF in the derived bucket.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "exported_to_email",
                    models.EmailField(
                        blank=True,
                        help_text="Captured initiator, never a group inbox (FR-10).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "line_group",
                    models.CharField(
                        choices=[
                            ("DOOR", "DOOR"),
                            ("RESTROOM_ACCESSORIES", "RESTROOM_ACCESSORIES"),
                            ("FREIGHT", "FREIGHT"),
                            ("OTHER", "OTHER"),
                        ],
                        db_index=True,
                        default="DOOR",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("unit", models.CharField(default="EA", max_length=50)),
                ("line_order", models.IntegerField(default=0)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=12
                    ),
                ),
                (
                    "our_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Human-entered or sourced through the waterfall.",
                        max_digits=12,
                    ),
                ),
                (
                    "margin_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Human-editable.",
                        max_digits=6,
                    ),
                ),
                (
                    "cost_source",
                    models.CharField(
                        choices=[
                            ("P21_LAST_PO", "P21_LAST_PO"),
                            ("DISTRIBUTOR_SHEET", "DISTRIBUTOR_SHEET"),
                            ("MFR_LIST", "MFR_LIST"),
                            ("VENDOR_RFQ", "VENDOR_RFQ"),
                            ("MANUAL", "MANUAL"),
                        ],
                        default="MANUAL",
                        help_text="Which waterfall path produced this cost. MANUAL is first-class (Risk R3).",
                        max_length=50,
                    ),
                ),
                ("cost_effective_date", models.DateField(blank=True, null=True)),
                (
                    "cost_is_stale",
                    models.BooleanField(
                        default=False,
                        help_text="Computed against COST_FRESHNESS_MONTHS (configurable, not hardcoded). Surfaces NR-2's 'price may be out of date - refresh' prompt. There is NO automatic silent refresh: a price that changes underneath an estimator without their knowledge is exactly the failure NFR-10 is about.",
                    ),
                ),
                (
                    "p21_reference",
                    models.CharField(
                        blank=True,
                        help_text="The matched P21 record, always surfaced so the estimator can reject it (R3).",
                        max_length=255,
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Copied onto the line, not just referenced, so the quote reproduces later.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "multiplier_sheet_version",
                    models.CharField(
                        blank=True,
                        help_text="NFR-3 requires the sheet version AND the tier.",
                        max_length=255,
                    ),
                ),
                (
                    "adders",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Manual adders outside the base price book (NR-4): electrification, non-removable-pin hinges, premium and lead-time finishes.",
                    ),
                ),
                (
                    "total_adders",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("margin_overridden", models.BooleanField(default=False)),
                (
                    "margin_override_reason",
                    models.TextField(
                        blank=True,
                        help_text="e.g. the confirmed sourcing-driven Wendy's case.",
                    ),
                ),
                (
                    "below_floor_flag",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="FR-15: the FLAG, not the workflow. CBC deferred approval routing (C13/R4).",
                    ),
                ),
                (
                    "sale_each",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "extended",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Group subtotal snapshot at the time of pricing.",
                        max_digits=14,
                    ),
                ),
                ("is_direct_equal", models.BooleanField(default=False)),
                ("substitution_note", models.TextField(blank=True)),
                ("needs_review", models.BooleanField(db_index=True, default=False)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="catalog.catalogitem",
                    ),
                ),
                (
                    "margin_band",
                    models.ForeignKey(
                        blank=True,
                        help_text="The default this line's margin came from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="pricing.marginband",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="openings.match",
                    ),
                ),
                (
                    "opening",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="openings.opening",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="quotes.quote",
                    ),
                ),
                (
                    "vendor_multiplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="pricing.vendormultiplier",
                    ),
                ),
            ],
            options={
                "ordering": ["quote", "line_group", "line_order"],
            },
        ),
        migrations.CreateModel(
            name="VendorRFQ",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "REQUESTED"),
                            ("RECEIVED", "RECEIVED"),
                            ("DECLINED", "DECLINED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="REQUESTED",
                        max_length=50,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("request_notes", models.TextField(blank=True)),
                (
                    "returned_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "price_may_be_stale",
                    models.BooleanField(
                        default=False,
                        help_text="Drives NR-2's 'price may be out of date - refresh' prompt.",
                    ),
                ),
                (
                    "quote_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfqs",
                        to="quotes.quoteline",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_rfqs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["project", "status"], name="quotes_quot_project_d51716_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["status", "created_at"], name="quotes_quot_status_9e9d33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoteline",
            index=models.Index(
                fields=["quote", "line_group", "line_order"],
                name="quotes_quot_quote_i_78982a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quoteline",
            index=models.Index(
                fields=["quote", "needs_review"], name="quotes_quot_quote_i_84fb55_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("margin_pct__lt", 1)),
                name="ck_line_margin_below_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("margin_overridden", False),
                    models.Q(("margin_override_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_override_requires_reason",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorrfq",
            index=models.Index(
                fields=["quote_line", "status"], name="quotes_vend_quote_l_4482a0_idx"
            ),
        ),
    ]
