# Generated by Django 5.2.17 on 2026-08-24 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_hardware_set_components'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='hardware_component',
            field=models.ForeignKey(blank=True, help_text="Set when this line came from resolving the opening's hardware-set callout (§5.11). Hardware is most of a real CBC quote, and this is the link that carries an HW-3 line back to the spec text that defined it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='openings.hardwaresetcomponent'),
        ),
    ]
