# Generated by Django 5.2.17 on 2026-08-19 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("BID_SET", "BID_SET"),
                            ("ADDENDUM", "ADDENDUM"),
                            ("SPEC", "SPEC"),
                            ("RFP", "RFP"),
                            ("OTHER", "OTHER"),
                        ],
                        default="BID_SET",
                        help_text="ADDENDUM is retained but is NOT by itself an answer to FR-14 (Risk R2): CBC has not said whether an addendum is a new document, a revision, or both. No reconciliation logic keys off this field.",
                        max_length=50,
                    ),
                ),
                (
                    "file_key",
                    models.CharField(
                        help_text="S3 key in the source bucket. Built by shared.s3_keys only.",
                        max_length=1024,
                    ),
                ),
                (
                    "file_version_id",
                    models.CharField(
                        blank=True,
                        help_text="S3 object version-ID captured at upload; part of the OCR idempotency key (B8).",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True,
                        help_text="Computed at upload and matched against S3's own checksum.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "UPLOADED"),
                            ("READY_FOR_PROCESSING", "READY_FOR_PROCESSING"),
                            ("PROCESSING", "PROCESSING"),
                            ("PROCESSED", "PROCESSED"),
                            ("FAILED", "FAILED"),
                            ("QUARANTINED", "QUARANTINED"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        help_text="Transition INTO READY_FOR_PROCESSING is the Django-to-worker handoff trigger (§3.2 rule 2) — the post_save signal enqueues to SQS on that transition and no other.",
                        max_length=50,
                    ),
                ),
                (
                    "status_detail",
                    models.TextField(
                        blank=True,
                        help_text="Why the document failed or was quarantined. Shown to the estimator.",
                    ),
                ),
                (
                    "ocr_result_key",
                    models.CharField(
                        blank=True,
                        help_text="Persisted raw OCR JSON, gzipped.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "ocr_result_version_id",
                    models.CharField(
                        blank=True,
                        help_text="S3 version, so a re-run is distinguishable from an overwrite.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        blank=True, help_text="From the manifest.", null=True
                    ),
                ),
                (
                    "manifest_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Preprocessing finished before OCR was attempted. §4.1 makes this an invariant, not a convenience: the manifest is the audit answer to 'why didn't the system read page 47?'",
                    ),
                ),
                ("is_encrypted", models.BooleanField(default=False)),
                (
                    "was_repaired",
                    models.BooleanField(
                        default=False,
                        help_text="pikepdf repaired a structurally damaged file into derived; source untouched (§4.2).",
                    ),
                ),
                (
                    "split_part_count",
                    models.IntegerField(
                        default=1,
                        help_text="Parts the document was split into for Textract's limits (§4.6).",
                    ),
                ),
                (
                    "estimated_ocr_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Logged BEFORE the spend, so MAX_OCR_COST_PER_DOCUMENT_USD can veto it (§10.3).",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "EMAIL"),
                            ("MANUAL", "MANUAL"),
                            ("PHONE", "PHONE"),
                        ],
                        default="MANUAL",
                        help_text="How the bid arrived. PHONE covers the NR-5 'create new bid request' path.",
                        max_length=50,
                    ),
                ),
                ("initiator_email", models.EmailField(max_length=255)),
                (
                    "rfp_body_text",
                    models.TextField(
                        blank=True,
                        help_text="Unstructured RFP context from the intake email.",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "architect",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "general_contractor",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "initiator_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the initiator is a known internal user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipelineJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PREPROCESS", "PREPROCESS"),
                            ("OCR", "OCR"),
                            ("NORMALIZE", "NORMALIZE"),
                            ("EXTRACT", "EXTRACT"),
                            ("LINK", "LINK"),
                            ("MATCH", "MATCH"),
                            ("PRICE", "PRICE"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("STARTED", "STARTED"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                            ("QUARANTINED", "QUARANTINED"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "attempt",
                    models.IntegerField(
                        default=0, help_text="Incremented on every delivery."
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="sha256(document_version_id + feature_set + route_config_version). SQS is at-least-once and a slow job WILL be redelivered; without this a retry storm double-bills Textract (bottleneck B8).",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "external_job_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Textract JobId. Written BEFORE the call is considered complete, so a redelivery resumes from the existing job instead of submitting a second one (B8).",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("error_detail", models.TextField(blank=True)),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "cost_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Cost per bid set is a first-class metric — see 'make cost-report' (§10.3).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_jobs",
                        to="projects.document",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_jobs",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="BidAlternate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="'BASE', 'Alternate 1', ...", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_base_bid", models.BooleanField(default=False)),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bid_alternates",
                        to="projects.document",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bid_alternates",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentManifest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        help_text="Document-global, 1-based. Split parts are offset back before writing (§4.6)."
                    ),
                ),
                (
                    "page_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="sha256 of the normalised page content stream; drives addendum diffing (§4.7).",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("width_pt", models.FloatField(blank=True, null=True)),
                ("height_pt", models.FloatField(blank=True, null=True)),
                (
                    "rotation",
                    models.IntegerField(
                        default=0,
                        help_text="Applied at raster time. A rotated sheet rendered without it produces polygons that overlay 90 degrees off — the single most common cause of 'the highlight is in the wrong place' (§4.5).",
                    ),
                ),
                (
                    "text_layer",
                    models.CharField(
                        choices=[
                            ("RICH", "RICH"),
                            ("SPARSE", "SPARSE"),
                            ("NONE", "NONE"),
                            ("VECTOR_OUTLINED", "VECTOR_OUTLINED"),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                ("native_word_count", models.IntegerField(default=0)),
                ("vector_path_count", models.IntegerField(default=0)),
                (
                    "page_class",
                    models.CharField(
                        choices=[
                            ("DOOR_SCHEDULE", "DOOR_SCHEDULE"),
                            ("HARDWARE_SCHEDULE", "HARDWARE_SCHEDULE"),
                            ("FRAME_SCHEDULE", "FRAME_SCHEDULE"),
                            ("FINISH_SCHEDULE", "FINISH_SCHEDULE"),
                            ("SPEC_TEXT", "SPEC_TEXT"),
                            ("DRAWING", "DRAWING"),
                            ("TITLE", "TITLE"),
                            ("INDEX", "INDEX"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=50,
                    ),
                ),
                (
                    "class_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "class_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOOKMARK", "BOOKMARK"),
                            ("TITLE_BLOCK", "TITLE_BLOCK"),
                            ("KEYWORD", "KEYWORD"),
                            ("MODEL", "MODEL"),
                            ("MANUAL", "MANUAL"),
                        ],
                        help_text="Which tier resolved this page — lets the expensive tier be measured.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ocr_route",
                    models.CharField(
                        choices=[
                            ("TEXTRACT_TABLES", "TEXTRACT_TABLES"),
                            ("TEXTRACT_TEXT", "TEXTRACT_TEXT"),
                            ("NATIVE_TEXT", "NATIVE_TEXT"),
                            ("SKIP", "SKIP"),
                        ],
                        db_index=True,
                        default="SKIP",
                        max_length=50,
                    ),
                ),
                (
                    "route_reason",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable justification, always surfaced for SKIP. Design rule: never silently skip (§4.3).",
                        max_length=255,
                    ),
                ),
                (
                    "raster_key",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("thumb_key", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "ocr_input_key",
                    models.CharField(
                        blank=True,
                        help_text="300 DPI render, only for VECTOR_OUTLINED pages routed to OCR (Risk R11).",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "ocr_cost_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("page_offset", models.IntegerField(default=0)),
                ("split_part", models.IntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifest_pages",
                        to="projects.document",
                    ),
                ),
                (
                    "forced_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="An estimator overrode the routing decision — 'read page 47 anyway' (Risk R12).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forced_page_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["document", "page_number"],
                "indexes": [
                    models.Index(
                        fields=["document", "ocr_route"],
                        name="projects_do_documen_9ecb71_idx",
                    ),
                    models.Index(
                        fields=["document", "page_class"],
                        name="projects_do_documen_e23388_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "page_number"), name="uniq_manifest_page"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PageDiff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNCHANGED", "UNCHANGED"),
                            ("CHANGED", "CHANGED"),
                            ("ADDED", "ADDED"),
                            ("REMOVED", "REMOVED"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "compared_to_document",
                    models.ForeignKey(
                        help_text="The earlier document being compared against.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_diffs_against",
                        to="projects.document",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_diffs",
                        to="projects.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document", "status"],
                        name="projects_pa_documen_a05095_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "compared_to_document", "page_number"),
                        name="uniq_page_diff",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["brand", "architect"], name="projects_pr_brand_ad58e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["general_contractor"], name="projects_pr_general_f35020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinejob",
            index=models.Index(
                fields=["document", "stage", "status"],
                name="projects_pi_documen_dd5160_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinejob",
            index=models.Index(
                fields=["status", "created_at"], name="projects_pi_status_44ccc1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinejob",
            constraint=models.UniqueConstraint(
                fields=("document", "stage"), name="uniq_job_document_stage"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["project", "status"], name="projects_do_project_624c06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "created_at"], name="projects_do_status_113219_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("project", "filename", "version"), name="uniq_document_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="bidalternate",
            constraint=models.UniqueConstraint(
                fields=("project", "designation"), name="uniq_alternate_designation"
            ),
        ),
    ]
