# Generated by Django 5.2.17 on 2026-08-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Bid due date, as given by the GC.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.CharField(blank=True, choices=[('WON', 'WON'), ('LOST', 'LOST')], db_index=True, help_text='WON or LOST once the bid is decided. Null while it is live.', max_length=10, null=True),
        ),
    ]
