# Generated by Django 5.2.17 on 2026-08-24 08:08

"""
Splitting is retired by triage-at-submission (§4.6 / C16).

The OCR stage now submits a PDF containing only the pages triage routed, so the
Textract 3,000-page limit is unreachable in practice and is enforced as a guard
in ``pipeline.stages.ocr.assert_within_limits`` rather than handled by splitting
a document into parts. Submitted-subset page N maps back to the document-global
page number through the sorted routed-page list, which is derived rather than
stored — so these two columns had no remaining reader.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_due_date_project_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmanifest',
            name='page_offset',
        ),
        migrations.RemoveField(
            model_name='documentmanifest',
            name='split_part',
        ),
    ]
