# Generated by Django 5.2.17 on 2026-08-19 12:41

import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThroatDepth",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wall_type",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "throat_depth_inches",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "is_custom",
                    models.BooleanField(
                        default=False,
                        help_text="True for manually entered values outside the five standards.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FinishCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "us_code",
                    models.CharField(
                        db_index=True,
                        help_text="Legacy US code, e.g. US26D.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "bhma_code",
                    models.CharField(
                        db_index=True,
                        help_text="BHMA numeric code, e.g. 626.",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "base_metal",
                    models.CharField(
                        blank=True,
                        help_text="brass / stainless / steel / nickel. Same base metal scores higher in matching.",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["bhma_code"], name="pricing_fin_bhma_co_e94b0f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("us_code", "bhma_code"), name="uniq_finish_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarginBand",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_type_band",
                    models.CharField(
                        choices=[
                            ("COMMODITY", "COMMODITY"),
                            ("RESTROOM_PARTITIONS", "RESTROOM_PARTITIONS"),
                            ("SPECIALTY", "SPECIALTY"),
                            ("CUSTOM_FABRICATED", "CUSTOM_FABRICATED"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_margin_pct",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fraction, e.g. 0.2700 for 27%.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "floor_margin_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Below this, quote lines set below_floor_flag (FR-15). Build the FLAG; build no approval workflow — CBC deferred routing (C13/R4).",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product_type_band", "-effective_date"],
                        name="pricing_mar_product_687005_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_type_band", "effective_date"),
                        name="uniq_margin_band_effective",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("target_margin_pct__lt", 1)),
                        name="ck_margin_below_one",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        db_index=True,
                        help_text="Two-letter state code, e.g. 'OH'.",
                        max_length=8,
                    ),
                ),
                (
                    "rate_pct",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fraction, e.g. 0.0800 for 8%.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "effective_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["jurisdiction", "-effective_date"],
                        name="pricing_tax_jurisdi_971bac_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("jurisdiction", "effective_date"),
                        name="uniq_tax_rate_effective",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorMultiplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_name", models.CharField(db_index=True, max_length=255)),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Standard'.",
                        max_length=100,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="0.29 = 71% off list.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "source_sheet_version",
                    models.CharField(
                        blank=True,
                        help_text="Which sheet this came from. Required by NFR-3.",
                        max_length=255,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor_name", "-effective_date"],
                        name="pricing_ven_vendor__2f60ae_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vendor_name", "tier", "effective_date"),
                        name="uniq_multiplier_effective",
                    )
                ],
            },
        ),
    ]
