# Generated by Django 5.2.17 on 2026-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormultiplier',
            name='note',
            field=models.TextField(blank=True, default='', help_text='What an estimator should know.'),
        ),
        migrations.AddField(
            model_name='vendormultiplier',
            name='protected_until',
            field=models.DateField(blank=True, help_text="The date CBC's cost is held to. Past it a mid-year list increase reaches the quote, so a lapsed protection is a reason to confirm before a proposal goes out — not merely a stale date.", null=True),
        ),
        migrations.AddField(
            model_name='vendormultiplier',
            name='reviewed_on',
            field=models.DateField(blank=True, help_text='When someone last checked this against the vendor.', null=True),
        ),
        migrations.AddField(
            model_name='vendormultiplier',
            name='sheet_name',
            field=models.CharField(blank=True, default='', help_text="The programme as purchasing refers to it, e.g. 'Hager L3 Program'.", max_length=255),
        ),
        migrations.AddField(
            model_name='vendormultiplier',
            name='steward',
            field=models.CharField(blank=True, default='', help_text='Who owns this sheet. Blank is the honest answer while NFR-10 is open.', max_length=255),
        ),
    ]
