# Generated by Django 5.2.17 on 2026-08-19 12:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("pricing", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocElement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The element_id the model cites.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "element_path",
                    models.CharField(
                        help_text="Positional pointer, e.g. 'pages/3/words/412' or 'tables/0/cells/17'. NATURAL KEY. Textract mints a fresh Block.Id on every job, so positional paths are what make normalisation idempotent and let a re-run re-link deterministically instead of orphaning citations (§7.2).",
                        max_length=255,
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        help_text="Document-global, after any split-part offset is applied (§4.6)."
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("word", "WORD"),
                            ("line", "LINE"),
                            ("table_cell", "TABLE_CELL"),
                            ("selection_mark", "SELECTION_MARK"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("x0", models.FloatField(blank=True, null=True)),
                ("y0", models.FloatField(blank=True, null=True)),
                ("x1", models.FloatField(blank=True, null=True)),
                ("y1", models.FloatField(blank=True, null=True)),
                ("x2", models.FloatField(blank=True, null=True)),
                ("y2", models.FloatField(blank=True, null=True)),
                ("x3", models.FloatField(blank=True, null=True)),
                ("y3", models.FloatField(blank=True, null=True)),
                ("bbox_x_min", models.FloatField(blank=True, null=True)),
                ("bbox_y_min", models.FloatField(blank=True, null=True)),
                ("bbox_x_max", models.FloatField(blank=True, null=True)),
                ("bbox_y_max", models.FloatField(blank=True, null=True)),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Scaled 0-1 from Textract's 0-100. NEVER recomputed, never overwritten — it is one half of the composite confidence and must stay attributable.",
                        null=True,
                    ),
                ),
                ("reading_order", models.IntegerField(blank=True, null=True)),
                (
                    "table_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Groups the cells of one table; scopes extraction batches.",
                        null=True,
                    ),
                ),
                (
                    "row_index",
                    models.IntegerField(
                        blank=True,
                        help_text="0-indexed (Textract is 1-indexed; normalised down).",
                        null=True,
                    ),
                ),
                ("col_index", models.IntegerField(blank=True, null=True)),
                ("column_header", models.BooleanField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="projects.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="The RESOLVED Bedrock model or inference-profile ID (C5). Never a hardcoded string: a run that cannot name its exact model version cannot be audited.",
                        max_length=255,
                    ),
                ),
                (
                    "model_id_cheap",
                    models.CharField(
                        blank=True,
                        help_text="Haiku tier used for Pass A locate (§5.3).",
                        max_length=255,
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        help_text="Resolves to llm/prompts/extraction/<version>.md — never edited in place.",
                        max_length=100,
                    ),
                ),
                (
                    "inference_params",
                    models.JSONField(
                        default=dict,
                        help_text="temperature, top_p, max_tokens. temperature is 0 (§5.4).",
                    ),
                ),
                (
                    "ocr_result_version_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "route_config_version",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the OCR routing table in force (§4.4).",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "STARTED"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="STARTED",
                        max_length=50,
                    ),
                ),
                ("error_detail", models.TextField(blank=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "cached_input_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="Prompt-cache hits; billed at roughly a tenth of standard (§5.12).",
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_runs",
                        to="projects.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldProvenance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(db_index=True, max_length=100)),
                (
                    "extracted_value",
                    models.TextField(
                        blank=True,
                        help_text="Null is a legitimate result — 'not present in the schedule' is a finding.",
                        null=True,
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, help_text="min across cited elements.", null=True
                    ),
                ),
                (
                    "llm_confidence",
                    models.FloatField(
                        blank=True, help_text="Model self-report.", null=True
                    ),
                ),
                (
                    "completeness_penalty",
                    models.FloatField(
                        default=1.0,
                        help_text="f(fields_populated / fields_expected). Stored, not just applied.",
                    ),
                ),
                (
                    "final_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="min(ocr, llm) * penalty. Can never exceed either input.",
                        null=True,
                    ),
                ),
                (
                    "grounding_score",
                    models.FloatField(
                        blank=True,
                        help_text="Value-grounding similarity against the cited text (§5.6).",
                        null=True,
                    ),
                ),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("bbox_x_min", models.FloatField(blank=True, null=True)),
                ("bbox_y_min", models.FloatField(blank=True, null=True)),
                ("bbox_x_max", models.FloatField(blank=True, null=True)),
                ("bbox_y_max", models.FloatField(blank=True, null=True)),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("AUTO", "AUTO"),
                            ("FLAGGED", "FLAGGED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("CORRECTED", "CORRECTED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        db_index=True,
                        default="AUTO",
                        max_length=50,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why the §5.6 validation gate rejected the field. Rejected fields are flagged for review, never repaired and never silently dropped.",
                        null=True,
                    ),
                ),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_provenance",
                        to="openings.extractionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldProvenanceElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ordinal", models.IntegerField(default=0)),
                (
                    "doc_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="citations",
                        to="openings.docelement",
                    ),
                ),
                (
                    "field_provenance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="openings.fieldprovenance",
                    ),
                ),
            ],
            options={
                "ordering": ["field_provenance", "ordinal"],
            },
        ),
        migrations.CreateModel(
            name="Opening",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "door_number",
                    models.CharField(
                        help_text="The key everything hangs off.", max_length=100
                    ),
                ),
                (
                    "size_raw",
                    models.CharField(
                        blank=True,
                        help_text="As written, e.g. '3070'.",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("width_inches", models.IntegerField(blank=True, null=True)),
                ("height_inches", models.IntegerField(blank=True, null=True)),
                (
                    "handing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LH", "LH"),
                            ("RH", "RH"),
                            ("LHR", "LHR"),
                            ("RHR", "RHR"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "handing_absent",
                    models.BooleanField(
                        default=False,
                        help_text="EXPLICIT. 'No handing found' must be distinguishable from 'not yet extracted' and from null — a null cannot carry three states (FR-8).",
                    ),
                ),
                ("finish_raw", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "fire_rating_raw",
                    models.CharField(
                        blank=True,
                        help_text="As written: '90 MIN', '1-1/2 HR', 'B LABEL'.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "fire_rating_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="20 / 45 / 60 / 90 only. Unrecognised flags; NEVER defaults to unrated.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                ("fire_rating_absent", models.BooleanField(default=False)),
                (
                    "fire_rating_source_location",
                    models.CharField(
                        choices=[
                            ("DOOR_SCHEDULE", "DOOR_SCHEDULE"),
                            ("FRAME_SCHEDULE", "FRAME_SCHEDULE"),
                            ("SPEC", "SPEC"),
                            ("MARGIN_NOTE", "MARGIN_NOTE"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="UNKNOWN",
                        help_text="Accumulates the empirical answer to Open Item 9 — CBC has not said where ratings live on their bid sets, so the system observes it (§5.8, Risk R1).",
                        max_length=50,
                    ),
                ),
                (
                    "hardware_group",
                    models.CharField(
                        blank=True,
                        help_text="'HW-3', or an explicit manufacturer part/series callout — both are normal (§1.3).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "alternate_designation",
                    models.CharField(
                        blank=True,
                        help_text="Free text as written.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("wall_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("AUTO", "AUTO"),
                            ("FLAGGED", "FLAGGED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("CORRECTED", "CORRECTED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        db_index=True,
                        default="AUTO",
                        max_length=50,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                (
                    "bid_alternate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Flag-gated (§7.6). Populated but not reconciled until Open Item 11 lands.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="openings",
                        to="projects.bidalternate",
                    ),
                ),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openings",
                        to="openings.extractionrun",
                    ),
                ),
                (
                    "finish_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="US19 and US26D must never collapse to the same row (§1.3).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="openings",
                        to="pricing.finishcode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openings",
                        to="projects.project",
                    ),
                ),
                (
                    "throat_depth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="openings",
                        to="pricing.throatdepth",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.IntegerField(help_text="1 = best.")),
                ("match_confidence", models.FloatField()),
                (
                    "rating_ok",
                    models.BooleanField(
                        help_text="A rated opening never matches an unrated item, regardless of text similarity."
                    ),
                ),
                (
                    "handing_ok",
                    models.BooleanField(
                        help_text="An LH opening never matches an RH-only SKU."
                    ),
                ),
                (
                    "division_ok",
                    models.BooleanField(
                        default=True,
                        help_text="A Division 10 accessory never matches a Division 08 opening.",
                    ),
                ),
                ("finish_ok", models.BooleanField()),
                ("finish_score", models.FloatField(default=0.0)),
                ("size_score", models.FloatField(default=0.0)),
                ("vendor_score", models.FloatField(default=0.0)),
                ("stock_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "PROPOSED"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("MANUAL", "MANUAL"),
                            ("AWAITING_RFQ", "AWAITING_RFQ"),
                        ],
                        db_index=True,
                        default="PROPOSED",
                        max_length=50,
                    ),
                ),
                (
                    "is_direct_equal",
                    models.BooleanField(
                        default=False,
                        help_text="The system RECORDS a substitution; it never decides one. Choosing an equal is estimator judgment (§1.4).",
                    ),
                ),
                ("substitution_note", models.TextField(blank=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Which constraint failed, in words the estimator can act on.",
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="catalog.catalogitem",
                    ),
                ),
                (
                    "opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="openings.opening",
                    ),
                ),
            ],
            options={
                "ordering": ["opening", "rank"],
            },
        ),
        migrations.AddField(
            model_name="fieldprovenance",
            name="opening",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable so non-opening extractions reuse the same mechanism.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provenance",
                to="openings.opening",
            ),
        ),
        migrations.AddIndex(
            model_name="docelement",
            index=models.Index(
                fields=["document", "page_number"],
                name="openings_do_documen_b4906d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="docelement",
            index=models.Index(
                fields=["table_id"], name="openings_do_table_i_a0b1e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="docelement",
            index=models.Index(
                fields=["document", "table_id", "row_index", "col_index"],
                name="openings_do_documen_3d84d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="docelement",
            index=models.Index(
                fields=["bbox_x_min", "bbox_y_min", "bbox_x_max", "bbox_y_max"],
                name="openings_do_bbox_x__02f0a6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="docelement",
            constraint=models.UniqueConstraint(
                fields=("document", "element_path"),
                name="uniq_element_path_per_document",
            ),
        ),
        migrations.AddIndex(
            model_name="extractionrun",
            index=models.Index(
                fields=["document", "status"], name="openings_ex_documen_03b3e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractionrun",
            index=models.Index(
                fields=["prompt_version", "model_id"],
                name="openings_ex_prompt__aaf495_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldprovenanceelement",
            index=models.Index(
                fields=["field_provenance", "ordinal"],
                name="openings_fi_field_p_6de0a2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldprovenanceelement",
            constraint=models.UniqueConstraint(
                fields=("field_provenance", "doc_element"), name="uniq_citation"
            ),
        ),
        migrations.AddIndex(
            model_name="opening",
            index=models.Index(
                fields=["project", "door_number"], name="openings_op_project_d3528c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opening",
            index=models.Index(
                fields=["extraction_run", "door_number"],
                name="openings_op_extract_186bd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opening",
            index=models.Index(
                fields=["project", "review_state"],
                name="openings_op_project_ef0c4a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="opening",
            constraint=models.UniqueConstraint(
                fields=("project", "extraction_run", "door_number"),
                name="uniq_opening_per_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="opening",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fire_rating_absent", False),
                    ("fire_rating_minutes__isnull", True),
                    _connector="OR",
                ),
                name="ck_rating_absent_excludes_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="opening",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("handing_absent", False),
                    ("handing__isnull", True),
                    _connector="OR",
                ),
                name="ck_handing_absent_excludes_value",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["opening", "rank"], name="openings_ma_opening_9bfb3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["opening", "status"], name="openings_ma_opening_c6963d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("opening", "catalog_item"), name="uniq_match_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldprovenance",
            index=models.Index(
                fields=["opening", "field_name"], name="openings_fi_opening_f11f26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldprovenance",
            index=models.Index(
                fields=["extraction_run", "review_state"],
                name="openings_fi_extract_4fba2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldprovenance",
            index=models.Index(
                fields=["review_state", "field_name"],
                name="openings_fi_review__e5a83b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldprovenance",
            constraint=models.UniqueConstraint(
                fields=("extraction_run", "opening", "field_name"),
                name="uniq_provenance_per_field",
            ),
        ),
    ]
