# Generated by Django 5.2.17 on 2026-08-24 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('openings', '0001_initial'),
        ('projects', '0003_drop_manifest_split_bookkeeping'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareSetComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hardware_group', models.CharField(db_index=True, help_text="The callout as written, e.g. 'HW-3'.", max_length=100)),
                ('component_index', models.IntegerField(default=0, help_text='Order within the set, as the specification lists it.')),
                ('resolved', models.BooleanField(default=False, help_text='False when the callout appears in the door schedule but its definition is not in this document. Never filled in from general knowledge (§5.11).')),
                ('explicit_part', models.BooleanField(default=False, help_text='The architect named a manufacturer part or series instead of a set. Not a resolution failure — the normal case (§1.3).')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('finish_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Parsed from quantity_raw. Null when the source did not state one.', max_digits=10, null=True)),
                ('review_state', models.CharField(choices=[('AUTO', 'AUTO'), ('FLAGGED', 'FLAGGED'), ('CONFIRMED', 'CONFIRMED'), ('CORRECTED', 'CORRECTED'), ('REJECTED', 'REJECTED')], db_index=True, default='AUTO', max_length=50)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['hardware_group', 'component_index'],
            },
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['opening', 'hardware_component', 'rank']},
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='uniq_match_pair',
        ),
        migrations.AddField(
            model_name='hardwaresetcomponent',
            name='extraction_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_components', to='openings.extractionrun'),
        ),
        migrations.AddField(
            model_name='hardwaresetcomponent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_components', to='projects.project'),
        ),
        migrations.AddField(
            model_name='fieldprovenance',
            name='hardware_component',
            field=models.ForeignKey(blank=True, help_text='Set instead of ``opening`` for a hardware-set component (§5.11). Cross-schedule resolution runs through the same validation gate and the same provenance chain as opening extraction — there is only one contract.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='openings.hardwaresetcomponent'),
        ),
        migrations.AddField(
            model_name='match',
            name='hardware_component',
            field=models.ForeignKey(blank=True, help_text='Null for the door itself; set for one component of the hardware set that opening calls for (§5.11). The opening is recorded either way, because the rating and handing hard constraints belong to the opening — the same HW-3 on a 90-minute door and on an unrated one are not the same match.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='openings.hardwaresetcomponent'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['hardware_component', 'rank'], name='openings_ma_hardwar_9f8975_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('opening', 'hardware_component', 'catalog_item'), name='uniq_match_pair', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='hardwaresetcomponent',
            index=models.Index(fields=['project', 'hardware_group'], name='openings_ha_project_1e71ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='hardwaresetcomponent',
            constraint=models.UniqueConstraint(fields=('extraction_run', 'hardware_group', 'component_index'), name='uniq_hardware_component_per_run'),
        ),
        migrations.AddConstraint(
            model_name='hardwaresetcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('resolved', True), ('description', ''), _connector='OR'), name='ck_unresolved_component_has_no_description'),
        ),
    ]
