# Generated by Django 5.2.17 on 2026-08-24 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_hardware_set_components'),
        ('pricing', '0002_vendormultiplier_note_and_more'),
        ('projects', '0003_drop_manifest_split_bookkeeping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opening',
            name='uniq_opening_per_run',
        ),
        migrations.AddField(
            model_name='opening',
            name='cell_label',
            field=models.CharField(blank=True, default='', help_text="Where on the sheet, e.g. 'Row 4'.", max_length=64),
        ),
        migrations.AddField(
            model_name='opening',
            name='csi_division',
            field=models.CharField(blank=True, default='', help_text="Full CSI section, e.g. '08 11 00' or '10 28 00'. The quote groups by this.", max_length=16),
        ),
        migrations.AddField(
            model_name='opening',
            name='description',
            field=models.TextField(blank=True, default='', help_text="The item as printed on the sheet. The ledger's widest column."),
        ),
        migrations.AddField(
            model_name='opening',
            name='duplicate_note',
            field=models.TextField(blank=True, default='', help_text='Why these two look like the same item.'),
        ),
        migrations.AddField(
            model_name='opening',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='The other reading of the same physical item — most often a base schedule row and the addendum that reissued it. Both rows are kept until an estimator says which to price: dropping one automatically would decide a question the documents genuinely leave open.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='openings.opening'),
        ),
        migrations.AddField(
            model_name='opening',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="How many the document says. Distinct from the quote line's quantity, which an estimator may change without altering what was read.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='opening',
            name='quote_text',
            field=models.TextField(blank=True, default='', help_text='The line as it will print on the proposal, before pricing.'),
        ),
        migrations.AddField(
            model_name='opening',
            name='sheet_label',
            field=models.CharField(blank=True, default='', help_text="Sheet number, e.g. 'A-601'.", max_length=64),
        ),
        migrations.AddField(
            model_name='opening',
            name='source_kind',
            field=models.CharField(choices=[('EXTRACTED', 'EXTRACTED'), ('REVIEW', 'REVIEW'), ('DUPLICATE', 'DUPLICATE'), ('MANUAL', 'MANUAL')], db_index=True, default='EXTRACTED', help_text='How the ledger presents this row and which quick action it offers. Distinct from review_state, which is about one field passing the gate.', max_length=20),
        ),
        migrations.AlterField(
            model_name='opening',
            name='door_number',
            field=models.CharField(blank=True, help_text='The mark, where the item has one. Null for a grab bar or a mirror.', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='opening',
            constraint=models.UniqueConstraint(fields=('project', 'extraction_run', 'door_number', 'sheet_label', 'cell_label'), name='uniq_opening_per_run'),
        ),
        migrations.AddConstraint(
            model_name='opening',
            constraint=models.CheckConstraint(condition=models.Q(('duplicate_of', models.F('id')), _negated=True), name='ck_duplicate_is_another_row'),
        ),
    ]
