# Generated by Django 5.2.17 on 2026-08-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0003_remove_opening_uniq_opening_per_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='extraction_run',
            field=models.ForeignKey(blank=True, help_text='Null for an item an estimator typed in. Attributing a hand-written line to a model run would claim a provenance it does not have, which is the same class of untruth §5.6 rejects a fabricated citation for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='openings.extractionrun'),
        ),
    ]
