# Generated by Django 5.2.17 on 2026-08-24 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0004_alter_opening_extraction_run'),
        ('projects', '0003_drop_manifest_split_bookkeeping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableExtraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_id', models.CharField(db_index=True, max_length=64)),
                ('prompt_version', models.CharField(max_length=32)),
                ('model_id', models.CharField(help_text='The resolved model that answered. A cached answer is attributable (C5).', max_length=255)),
                ('payload', models.JSONField(default=list, help_text='The opening records the model returned, exactly as returned.')),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cached_input_tokens', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_extractions', to='projects.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'prompt_version'], name='openings_ta_documen_5de5a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'table_id', 'prompt_version'), name='uniq_table_extraction')],
            },
        ),
    ]
