# Generated by Django 5.2.17 on 2026-08-19 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor", models.CharField(db_index=True, max_length=255)),
                (
                    "series",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Hager 3400 vs 3500 — ANSI/BHMA Grade 1 vs Grade 2. Not interchangeable.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=255)),
                (
                    "part_number",
                    models.CharField(
                        blank=True,
                        help_text="Explicit manufacturer part.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Manufacturer list. Multiplied by the vendor tier to reach cost (§6.2 step 2).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("list_price_effective_date", models.DateField(blank=True, null=True)),
                (
                    "list_price_sheet_version",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "product_type_band",
                    models.CharField(
                        choices=[
                            ("COMMODITY", "COMMODITY"),
                            ("RESTROOM_PARTITIONS", "RESTROOM_PARTITIONS"),
                            ("SPECIALTY", "SPECIALTY"),
                            ("CUSTOM_FABRICATED", "CUSTOM_FABRICATED"),
                        ],
                        default="COMMODITY",
                        help_text="Drives the margin band.",
                        max_length=50,
                    ),
                ),
                (
                    "line_group",
                    models.CharField(
                        choices=[
                            ("DOOR", "DOOR"),
                            ("RESTROOM_ACCESSORIES", "RESTROOM_ACCESSORIES"),
                            ("FREIGHT", "FREIGHT"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "csi_division",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="08 / 09 / 10. A Division 10 accessory never matches a Division 08 opening.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "fire_rating_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="20/45/60/90; null means unrated. HARD constraint.",
                        null=True,
                    ),
                ),
                (
                    "handing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LH", "LH"),
                            ("RH", "RH"),
                            ("LHR", "LHR"),
                            ("RHR", "RHR"),
                        ],
                        help_text="Null means the item is not handed. HARD constraint when set.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "is_stock",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="The top-10 list, extendable to ~20 (NR-6). NR-13: automate stock and top-N items; beyond that a clear MANUAL cut-off. The estimator owns the long tail by design, not by failure.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "p21_item_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="NULLABLE ON PURPOSE (Risk R3): P21 item IDs diverge from manufacturer part numbers and semi-custom items will not match cleanly. The system never auto-accepts a cost match on part-number similarity alone.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "finish_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_items",
                        to="pricing.finishcode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor", "series"],
                        name="catalog_cat_vendor_74269e_idx",
                    ),
                    models.Index(
                        fields=["is_stock", "is_active"],
                        name="catalog_cat_is_stoc_414227_idx",
                    ),
                    models.Index(
                        fields=["csi_division", "product_type_band"],
                        name="catalog_cat_csi_div_537720_idx",
                    ),
                    models.Index(
                        fields=["part_number"], name="catalog_cat_part_nu_c8f76e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vendor", "sku"), name="uniq_catalog_vendor_sku"
                    )
                ],
            },
        ),
    ]
