# Generated by Django 5.2.17 on 2026-08-24 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItemXref',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(db_index=True, help_text="e.g. 'ASI', 'Bradley'.", max_length=255)),
                ('part_number', models.CharField(db_index=True, max_length=255)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ['brand'],
                'indexes': [models.Index(fields=['part_number'], name='catalog_cat_part_nu_4f2c31_idx')],
                'constraints': [models.UniqueConstraint(fields=('catalog_item', 'brand', 'part_number'), name='uniq_xref_per_item')],
            },
        ),
    ]
