# Generated by Django 5.2.17 on 2026-08-24 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_drop_manifest_split_bookkeeping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('GC_CALL', 'GC_CALL'), ('ARCHITECT_CALL', 'ARCHITECT_CALL'), ('INTERNAL', 'INTERNAL')], db_index=True, default='INTERNAL', max_length=32)),
                ('who', models.CharField(blank=True, default='', help_text='Who was on the call.', max_length=255)),
                ('org', models.CharField(blank=True, default='', help_text='Their company.', max_length=255)),
                ('body', models.TextField(help_text='What was said. The whole point of the row.')),
                ('ref', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_logged', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='notes_note_project_250acf_idx')],
            },
        ),
    ]
