# Generated by Django 5.2.17 on 2026-08-21 12:21

from django.db import migrations, models


def set_role_from_is_staff(apps, schema_editor):
    """
    Existing rows predate the role column.

    is_staff was the only signal of admin-ness before this migration, so it is what
    the role is derived from here. After this, the direction reverses permanently:
    the model derives is_staff FROM role, and this is the one place the old
    direction is honoured.
    """
    User = apps.get_model("authentication", "User")
    User.objects.filter(is_staff=True).update(role="ADMIN")
    User.objects.filter(is_staff=False).update(role="ESTIMATOR")


def clear_role(apps, schema_editor):
    """Reversing drops the column; nothing to undo beyond that."""


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('ESTIMATOR', 'ESTIMATOR')], default='ESTIMATOR', help_text='ADMIN also stewards pricing and catalog data, and may open /admin/.', max_length=20),
        ),
        migrations.RunPython(set_role_from_is_staff, clear_role),
    ]
